#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <vector>
#include <string>
#include <wx/msgdlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/msgdlg.h>
#include "wx/dirdlg.h"
#include <wx/dir.h>
#include <wx/stattext.h>
#include <wx/bmpbuttn.h>
#include <wx/bitmap.h>
#include "FreeImage.h"
#include "wx/custombgwin.h"
#include "wx/wx.h"
#include <iostream>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/sizer.h>
#include <fstream>
#include "ImageButton.h"
#include "BigDisplay.h"
#include "IPTCCheckboxDialog.h"

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
protected:
	// Handlers for MyFrame1 events
	void MyFrame1OnSize(wxSizeEvent& event) override;
	void m_buttonLoadFileOnButtonClick(wxCommandEvent& event);
	void m_buttonSaveTextAllOnButtonClick(wxCommandEvent& event);
	void m_buttonSaveTextOnButtonClick(wxCommandEvent& event);
	void m_buttonSaveDataOnButtonClick(wxCommandEvent& event);
	void m_buttonRotateOnButtonClick(wxCommandEvent& event);
	void m_buttonSaveIPTCOnButtonClick(wxCommandEvent& event);
	void m_buttonLoadOnButtonClick(wxCommandEvent& event);
public:
	/** Constructor */
	GUIMyFrame1(wxWindow* parent);
	//// end generated class members

	int windowWidth;
	size_t fileCount;
	wxArrayString pathArray;
	std::vector<wxBitmap> bitmapVector;
	wxFlexGridSizer* buttonsSizer;

	BigDisplay* currentBigDisplay = nullptr;
	wxString currentImgPath = wxEmptyString;

	void printBitmapButtons();
	void Repaint(bool loading = true);

	static wxString getImageExifData(FIBITMAP* bitmap);
	static wxString getImageIPTCData(FIBITMAP* bitmap);
	static wxString getImageIPTCData(FIBITMAP* bitmap, const char* tagName);

	static void AddText(wxImage image, const wxString& text, const wxString& path);
	static void DrawTextOnWxImage(wxImage& image, const wxString& text, int x, int y, const wxFont& font, const wxColour& textColor);

	void DisplayBigImg(const wxString &path);
	void DisplayMetaData(const wxString &path);
	void DisplayFolder();

	friend class ImageButton;
	friend class BigDisplay;
};

#endif // __GUIMyFrame1__
